# Puerto 8082 para no chocar con el 8081 de inventario
server.port=8082
spring.application.name=guia-almacen-service

# Conexión a tu base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/db_vitivinicolas
spring.datasource.username=postgres
spring.datasource.password=

# Configuración de Hibernate para validar la tabla existente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true