spring.application.name=microservicio-caja

# Puerto del servidor
server.port=8081

# 1. Conexión a PostgreSQL - USA TU CONTRASEÑA
spring.datasource.url=jdbc:postgresql://localhost:5432/db_caja
spring.datasource.username=postgres
spring.datasource.password=postgresql17
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuración de Hibernate para Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true