server.port=8081
spring.application.name=inventory-service

# Conexión limpia a la base de datos de PostgreSQL sin contraseña
spring.datasource.url=jdbc:postgresql://localhost:5432/caso_vitivinicolas
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true